### ISSUE TITLE
[Epic] Network Info Wish List

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#3315]
This is a issue to collect what additional "network health" related data we would want to have available in the app api.

There is currently some network data exposed to the app api via the [network_info](https://docs.rs/holochain/0.3.0-beta-dev.35/holochain/conductor/api/struct.NetworkInfo.html) call.

There is currently a lot more network data exposed to the admin api, but not the app api. I made a separate issue to request it be exposed to the app api: https://github.com/holochain/holochain/issues/3314

For any *additional* network data you want access to, please add a comment, or edit this initial comment to add to the list.

## Network Info Wish List
- [ ] dht arc size clamp of peers (i.e. are they clamped to a full arc, or clamped to a 0 arc)
- [ ] dynamic dht arc size of peers (i.e. the number of peers responsible for storing & validating your actions)
- [ ] dynamic dht arc coverage of peers (i.e. how much of the arc's hash space can be served) 
- [ ] quantization hashes of peers & do my own quantization hashes match peers (i.e. do i know that i have the same dht ops for a given time period as peers, or not)

**Comment by ThetaSinner** [comment]
Between full arc and 0 arc, the default is for it to be dynamic. In that case, I wonder if knowing whether:

- The number of peers available who are responsible for storing and validating your actions
- The current 'coverage' which is already available internally, to know how much of the arc can currently be served by somebody. Or to put it another way, how much of the hash space is reachable for get requests. So if all the peers responsible for a segment of the DHT are offline and nobody is currently serving a full arc then you know there is at least some data you will have to rely on your cache for. This isn't the same as being able to access all data because you don't know the sync state of other nodes but it still might be useful to know.

**Comment by ddd-mtl** [comment]
+1

On my wish list I'd also add:
 - Number of actively connected peers
 
Don't know if its available in the admin api, but the `NetworkInfo.current_number_of_peers` doesnt represent the active connections from what I can tell.

I don't find the whole `NetworkInfo` data very useful tbh. Some documention on what the values represent would be useful.

**Comment by ThetaSinner** [comment]
This issue probably answers this comment https://github.com/holochain/holochain/issues/3314#issuecomment-2489075074

**Comment by jost-s** [comment]
depends on kitsune2

**Comment by ThetaSinner** [comment]
When refining this issue, please can we consider what overlap it might have with -> https://github.com/holochain/holochain/issues/4818. If we can expose anything that helps that issue then we should consider it while we're working on this one.

**Comment by mattyg** [comment]
Copied from https://github.com/holochain/holochain/issues/3251#issuecomment-2489020649
- Are we currently able to reach some peers for gossip? As a way to measure network connectivity
- Sync progress when first joining
