### ISSUE TITLE
Holochain workspace dependencies tracking issue

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3464]
The Holochain core team would like to use [workspace dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table). There are a few things we know we need to take care of to keep our build and automation working with this change. This issue tracks what we know and can be updated as we discover new problems.

- [ ] The `release-automation` tool, that is used for (among other things) bumping crate versions on release, does not know how to update dependencies in the workspace. This prevents us from moving project crates into the workspace dependencies.
- [ ] [Crane](https://github.com/ipetkov/crane) is more focused on single crates and not workspaces. One of its gaps is not being able to distinguish between project dependencies and external dependencies. This means that if we put our project dependencies at the workspace level we will cause constant rebuilds of all our dependencies on CI and wreak havoc with cachix. See https://github.com/ipetkov/crane/issues/445
- [ ] Change detection in the `release-automation` depends on checking the git changes for each crate. This breaks when you specify dependencies in the workspace and the crate just references it with `crate_name = { workspace = true }`. There is no source change in the crate when the version is bumped in the workspace so it will not be flagged for release. That means that new releases with updated dependencies will end up accidentally depending on older crates with mismatched dependencies.

**Comment by ThetaSinner** [comment]
I'm a little off here. Even without putting dependencies in our `workspace.dependencies` we have our project deps in the ` Cargo.lock`... That means we're already getting far more rebuilds and far more cache pushing than we should have

**Comment by steveej** [comment]
also see #3629 as an alternative option to implementing this feature in our custom tooling.

**Comment by jost-s** [comment]
will have to be enabled by new release automation
