### ISSUE TITLE
Make it possible to install an app with custom properties

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3918]
Currently, it doesn't seem to be possible to install an app with custom properties. 

- from the modifiers only the network seed is exposed through the InstallApp payload
- modifying the manifest of an AppBundle in Rust does not seem to be possible without actually unpacking the bundle to disk, modifying the yaml file on disk and then repackaging

Use case:

- In Moss we want to use the progenitor pattern for all groups, and without being able to pass in properties it's quite a bit of code to export and rebuild the AppBundle

[Related thread](https://chat.holochain.org/holo/pl/phbco78zffrh9xhjgyuthmfwpo)

#### TODO:
- [x] modify conductor API (TODO: modify enum variant format of UseExisting) (https://github.com/holochain/holochain/pull/4416, https://github.com/holochain/holochain/pull/4487)
- [x] add new option to tryorama
- [x] add option to hc sandbox to insall web-app with custom properties (https://github.com/holochain/holochain/pull/4455)
- [x] js-client (https://github.com/holochain/holochain-client-js/pull/298)
- [x] Rust client
- [x] functional tests (override properties correctly, in case of multiple roles, modify only for one role, dna hash should change based on the modifiers, does providing properties add or override properties, memproof deferred strategy is only used if `None` is provided for *all* roles)

**Comment by guillemcordoba** [comment]
Reopening because nothing was actually done, and 3 developers in the community including myself have been hitting this and been frustrated by it.

**Comment by ThetaSinner** [comment]
- Would be good to have this in the `hc` command somewhere, maybe pass a JSON input that could become the properties map?
- Current `network_seed` on `InstallAppPayload` applies to all DNAs in an app, this needs to be per DNA
- Add a HashMap of properties that overwrite what is in the manifest
- Key on the role name, rather than working with DNA hashes

**Comment by mattyg** [comment]
> Would be good to have this in the hc command somewhere, maybe pass a JSON input that could become the properties map?

Just noting my preference:

- The hc command takes a path to a yaml file instead of a JSON string. Dealing with string escaping for passing in JSON to a cli command is icky, and we're already using yaml for all other configs.

- The yaml file is a subset of the app manifest structure, such that it gets merged into the existing app manifest, overriding any conflicting keys.

**Comment by matthme** [comment]
Here's my implementation proposal:
* Add an additional field `modifiers` to the `InstallAppPayload` which is of type: `Option<HashMap<RoleName, DnaModifiersOpt<YamlProperties>>>`
* let the `network_seed` field as well and have the following order of precedence:
  - If a network seed is specified for a role in the `modifiers` field this will always take precedence
  - if a network seed is specified in the `network_seed` field, this will overwrite the network seed for all dnas that have do not have the network seed defined as part of the `modifiers` field
  * if a field is `None` in the `modifier` field (for example the `quantum_time` field), it will be taken from the manifest if present, i.e. *not* overwritten with `None` (which would then probably fall back to a default value?). This seems like the most debatable point to me.

**Comment by mattyg** [comment]
Noting that this is back in refinement so we can determine how much more work it would be to have all the settings that are keyed by role-name under a single Map (i.e. both `membrane_proofs` and `modifiers`)

**Comment by matthme** [comment]
After feedback that all "by-role-settings" should probably be unified in a single field in the `InstallAppPayload` for convenience, I made a [draft PR](https://github.com/holochain/holochain/pull/4416) now.

It is removing the `membrane_proofs` and `existing_cells` fields and instead adds a `role_settings` field to the `InstallAppPayload` that takes a `RoleSettingsMap` as input:
```
pub type RoleSettingsMap = HashMap<RoleName, RoleSettings>;

/// Settings for a Role that may be passed on installation of an app
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct RoleSettings {
    /// When the app being installed has the `allow_deferred_memproofs` manifest flag set,
    /// passing `None` for this field will allow the app to enter the "deferred membrane proofs"
    /// state, so that memproofs can be provided later via [`AppRequest::ProvideMemproofs`].
    /// If `Some` is used here, whatever memproofs are provided will be used, and the app will
    /// be installed as normal.
    pub membrane_proof: Option<MembraneProof>,
    /// Optional: Overwrites the dna modifiers from the dna manifets. Only
    /// modifier fields for which `Some(T)` is provided will be overwritten.
    pub modifiers: Option<DnaModifiersOpt<YamlProperties>>,
    /// For each role in the app manifest which has UseExisting cell provisioning,
    /// a CellId of a currently installed cell must be specified in this field.
    pub existing_cell: Option<CellId>,
}
```

**Comment by matthme** [comment]
Maybe we could call the enum variants `Existing` and `Provisioned`?

**Comment by guillemcordoba** [comment]
Yeah I find that using enums with `#[serde(tag = "type")]` is the way to go and makes for a clean typescript experience as well. I would love to have all the `holochain_client` types include that.

**Comment by matthme** [comment]
> I find that using enums with #[serde(tag = "type")] is the way to go and makes for a clean typescript experience as well. I would love to have all the holochain_client types include that.

I created an issue for this - hope we can get this in together with above breaking changes: https://github.com/holochain/holochain/issues/4420

**Comment by matthme** [comment]
Closing this now as completed. Forwarding the option to hc-spin / hc-launch are separate issues in the respective repositories (https://github.com/holochain/hc-spin/issues/15 and https://github.com/holochain/hc-launch/issues/1)
