### ISSUE TITLE
Countersigning fallout tracking

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#4268]
- [ ] lair not connecting, on holochain startup or becomes unresponsive - required lair restart
- [ ] warrants appearing, why? Is it countersigning entries?
- [ ] scheduled functions when the chain is locked, or possibly helped by restarts which we're now not doing
- [ ] "Other: Other(Other(RibosomeError(WasmRuntimeError(RuntimeError { source: User(WasmError { file: "crates/holochain/src/core/ribosome/host_fn/query.rs", line: 29, error: Host("Deserialize(\"missing field `type`\")") }), wasm_trace: [] }))))"

**Comment by jost-s** [comment]
these items are tracked elsewhere
